name: collevo_teacher
description: Teacher website for Collevo
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=3.0.6 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.8.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  firebase_storage: ^11.2.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  url_launcher: ^6.1.12
  shared_preferences: ^2.2.0
  fluro: ^2.0.5
  url_strategy: ^0.2.0
  charts_flutter_new: ^0.12.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500